image:
  file: .gitpod.Dockerfile
  
tasks:
- name: Start
  command: |
    go run .
ports:
    - name: Web App
      description: The main application web server
      port: 8080
      onOpen: open-browser